import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import Icon from '../components/Icon'

const API = 'http://127.0.0.1:8000'

function SafetyCommunications({ eventId }) {
  const [alerts, setAlerts] = useState([])
  const load = () => fetch(`${API}/dashboard-safety-alerts`).then((r) => r.json()).then((data) => setAlerts(data.alerts || [])).catch(() => {})
  useEffect(() => { load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer) }, [eventId])
  const update = (id, path) => fetch(`${API}/dashboard-alerts/${id}/${path}`, { method: 'PATCH' }).then(load)
  return <section className="dashboard-communications"><div className="dashboard-module-header"><div><span className="eyebrow">LIVE OPERATOR MESSAGES</span><h2>Active Safety Communications</h2></div><strong>{alerts.length} ACTIVE</strong></div>{alerts.length ? alerts.map((alert) => <article className={`dashboard-alert priority-${String(alert.priority).toLowerCase()}`} key={alert.id}><div className="dashboard-alert-top"><b>{alert.priority}</b><small>{new Date(alert.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></div><h3>{alert.title}</h3><p>{alert.message}</p><footer><span>Audience: {alert.audience} · Monitoring #{alert.monitoring_session_id}</span><button onClick={() => update(alert.id, 'read')}>MARK AS READ</button><button onClick={() => update(alert.id, 'dismiss')}>DISMISS</button></footer></article>) : <div className="dashboard-alert-empty">No active safety communications.</div>}</section>
}

function Dashboard() {
  const navigate = useNavigate(); const location = useLocation(); const authority = location.pathname.startsWith('/authority'); const actions = authority ? [['list', 'Submitted Events', 'View registered events submitted for official document review.', 'View Events', '/authority/events'], ['check', 'Document Review', 'Review uploaded documents and record official workflow remarks.', 'Open Reviews', '/authority/documents']] : [['plus', 'Event Registration', 'Create an event with the details used by the existing risk engine.', 'Register Event', '/events/register'], ['list', 'My Events', 'View details, edit your submission, or delete your own event.', 'Manage Events', '/events'], ['upload', 'Upload Documents', 'Submit required event documents and respond to reviewer remarks.', 'Upload Documents', '/organizer/documents'], ['list', 'Track Application Status', 'See document statuses, remarks, and the separate AI risk result.', 'Track Status', '/organizer/application-status']]
  const eventId = location.pathname.match(/^\/organizer\/events\/(\d+)/)?.[1] || '1'
  return <div className="app dashboard-app"><Navbar /><main className="dashboard-main"><div className="dashboard-topline"><span><i /> COMMAND CENTER</span><small>EXPLAINABLE CROWD RISK AI</small></div><section className="dashboard-hero-layout"><div className="dashboard-hero-copy"><div className="eyebrow">{authority ? 'AUTHORITY / REVIEWER WORKSPACE' : 'EVENT ORGANIZER WORKSPACE'}</div><h1>{authority ? <>Authority <span>Dashboard</span></> : <>Organizer <span>Dashboard</span></>}</h1><p>{authority ? 'Review submitted event documents and record official remarks.' : 'Register your event, submit documents, track review, and monitor safety operations.'}</p><div className="dashboard-hero-actions"><button className="dashboard-primary" onClick={() => navigate(actions[0][4])}>{actions[0][3]} <span>→</span></button><span className="dashboard-hint">{actions.length} operational modules available</span></div></div><div className="radar-panel glass-card"><div className="radar-panel-heading"><span>SAFETY INTELLIGENCE</span><small>CONTROL SURFACE / 01</small></div><div className="safety-radar"><div className="radar-grid-line horizontal" /><div className="radar-grid-line vertical" /><div className="radar-ring radar-ring-outer" /><div className="radar-ring radar-ring-middle" /><div className="radar-ring radar-ring-inner" /><div className="radar-sweep" /><div className="radar-core"><span>CG</span></div></div><div className="radar-footer"><span><i /> SYSTEM READY</span><small>LIVE MODULES CONNECTED</small></div></div></section>{!authority && <SafetyCommunications eventId={eventId} />}<section className="dashboard-module-header"><div><span className="eyebrow">WORKSPACE MODULES</span><h2>Move from planning to action.</h2></div><p>Use the connected workflow to prepare, submit and monitor event safety operations.</p></section><section className="action-grid">{actions.map(([icon, title, description, action, path], index) => <article className="action-card glass-card" key={title}><div className="action-card-top"><span className="card-index">0{index + 1}</span><span className="card-icon"><Icon name={icon} /></span></div><h3>{title}</h3><p>{description}</p><button onClick={() => navigate(path)}>{action} <span>→</span></button></article>)}</section></main><footer className="dashboard-footer">CrowdGuard <span>/</span> Planning and safety communication workspace</footer></div>
}

export default Dashboard
