import { useEffect, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import Navbar from '../components/Navbar'

function RiskResult() {
  const navigate = useNavigate(); const location = useLocation(); const { eventId } = useParams(); const [result, setResult] = useState(location.state?.result || null); const [error, setError] = useState('')
  useEffect(() => { if (!result && eventId) fetch(`http://127.0.0.1:8000/events/${eventId}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Unable to load risk result.'); setResult({ event_id: data.id, event_name: data.event_name, pre_event_risk: data.pre_event_risk }) }).catch((requestError) => setError(requestError.message)) }, [eventId, result])
  if (error) return <div className="app"><Navbar /><main className="empty-state"><div className="glass-card"><h2>Risk result unavailable</h2><p>{error}</p><button className="primary-btn" onClick={() => navigate('/events')}>Back to Events</button></div></main></div>
  if (!result) return <div className="app"><Navbar /><main className="empty-state"><div className="glass-card"><h2>Loading assessment…</h2></div></main></div>
  const risk = result.pre_event_risk; const riskClass = `risk-result-${risk.risk_level.toLowerCase()}`
  return <div className="app"><div className="background-grid" /><div className="glow glow-one" /><Navbar /><main className="page-main"><section className="page-heading"><div className="eyebrow"><span className="pulse-dot" />EXPLAINABLE RISK ASSESSMENT</div><h1>Pre-event <span>risk result</span></h1><p>Assessment for {result.event_name}. Review the factors behind this classification and the recommended safety actions.</p></section><section className="risk-summary"><article className="risk-card glass-card"><h2>{result.event_name}</h2><p>Event ID #{result.event_id}</p></article><article className={`risk-card risk-level glass-card ${riskClass}`}><small>RISK LEVEL</small><strong>{risk.risk_level}</strong><b>Score {risk.risk_score}</b></article></section><section className="risk-details"><article className="risk-card glass-card"><h3>Why this risk level?</h3><ul className="result-list">{risk.reasons.length ? risk.reasons.map((reason, index) => <li key={index}>{reason}</li>) : <li>No major risk factors detected.</li>}</ul></article><article className="risk-card glass-card"><h3>Safety recommendations</h3><ul className="result-list">{risk.recommendations.map((recommendation, index) => <li key={index}>{recommendation}</li>)}</ul></article></section><div className="risk-actions"><button className="primary-btn" onClick={() => navigate('/events/register')}>Register Another Event</button><button className="secondary-btn" onClick={() => navigate('/dashboard')}>Back to Dashboard</button></div></main><footer>CrowdGuard · Explainable pre-event risk assessment</footer></div>
}
export default RiskResult
